name: Automatic Approve

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  automatic_approve:
    runs-on: ubuntu-latest

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 77e8fd27c1 (Run auto approve only on qmk/qmk_firmware (#16786))
    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: mheap/automatic-approve-action@v1
      with:
        token: ${{ secrets.QMK_BOT_TOKEN }}
        workflows: "format.yml,lint.yml,unit_test.yml"
        dangerous_files: "lib/python/,Makefile,paths.mk,builddefs/"
=======
    steps:
<<<<<<< HEAD
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.QMK_BOT_TOKEN }}
          workflows: "format.yml,lint.yml,unit_test.yml"
          dangerous_files: "lib/python/,Makefile,paths.mk,builddefs/"
>>>>>>> bebccd1fd0 (Automatically approve workflow runs from first time contributors (#16774))
=======
    - uses: mheap/automatic-approve-action@v1
      with:
        token: ${{ secrets.QMK_BOT_TOKEN }}
        workflows: "format.yml,lint.yml,unit_test.yml"
        dangerous_files: "lib/python/,Makefile,paths.mk,builddefs/"
>>>>>>> c692102e24 (Automatically approve workflow runs from first time contributors (#16775))
